### ISSUE TITLE
markup visible in code snippet

### ISSUE THREAD

**Issue by falsifian** [Raku/doc#4250] opened 2023-03-04 22:19 UTC
## Problem

The code example in [the infix `ff` section of the operators page](https://docs.raku.org/language/operators.html#infix_%3F%3F_!!) includes this line:
```
    take $_ if <strong>"=begin code" ff "=end code"</strong>
```
I guess the `<strong>` isn't meant literally.

**Comment by cfa** [comment] 2023-03-04 22:35
Thanks @falsifian. This is a known issue with the renderer that is being worked on (see mention above).

FYI, the underlying POD in this instance is:

```raku
my @codelines = gather for $excerpt.lines {
    take $_ if B<"=begin code" ff "=end code">
}
# this will print four lines, starting with "=begin code" and ending with
# "=end code"
say @codelines.join("\n");
=end code
```

Note the `B<…>` (bold) markup that is incorrectly rendered using `<strong>…</strong>`.

**Comment by coke** [comment] 2023-03-05 18:01
Closing this as a duplicate of the linked ticket in doc/website; please follow there for updates.

**Closed by coke** 2023-03-05 18:01 UTC
Labels: docs
