### ISSUE TITLE
missing-methods.p6 no longer works

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3854] opened 2021-04-03 07:09 UTC
## Problem or new feature

It uses p6doc, which has been deprecated. So that's a problem.

## Suggestions

The functionality it uses might be elsewhere. Anyway, might be good to make #3819 work.

**Comment by coke** [comment] 2021-04-09 22:31
Duplicate of  #3812

**Closed by coke** 2021-04-09 22:31 UTC
Labels: docs
