### ISSUE TITLE
Perform more checks automatically and do automatic deployment if possible too.

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3451] opened 2020-05-31 18:03 UTC
## Problem or new feature

Automatic deployment has been already requested #3428 , but additionally, there are some lengthy checks, mainly test-compile examples and spell checks, which are not automated right now.

## Suggestions

Use GitHub actions or Azure DevOps pipelines to do both.

**Comment by coke** [comment] 2021-06-24 00:03
There are two items in this ticket; one is already listed as a duplicate, the second is a duplicate of #3036.

Closing ticket.

**Closed by coke** 2021-06-24 00:03 UTC
Labels: build, meta
