### ISSUE TITLE
Immediately view small changes in browser without rebuilding all pages

### ISSUE THREAD

**Issue by hakonhagland** [Raku/doc#2668] opened 2019-03-13 09:42 UTC
Say I make a small change to one of the `*.pod6` files in the `doc` folder, do I have to rebuild the
whole documentation with `make html` to view the change in my browser at http://127.0.0.1:3000/ ?

It seems it should be possible somehow to make small changes and see the result immediately without having to wait for the build (takes several minutes), but I could not find out how.

**Comment by JJ** [comment] 2019-03-13 13:09
It should, shouldn't it? Yet it's not possible. We are into a (slow) process of refactoring all the documentation tooling, and that would be one of our requirements. See #1823 and many other related issues. It's also an project in the Google Summer of Code, so we should expect to have something by Fall this year.

**Comment by AlexDaniel** [comment] 2019-06-25 19:27
Reopening because the issue is still there.

**Comment by treyharris** [comment] 2019-06-25 19:27
This should be left open until it is possible to do an incremental build.

**Comment by antoniogamiz** [comment] 2019-07-15 15:37
You can check the `update` option :D.

**Comment by treyharris** [comment] 2019-07-21 22:01
@antoniogamiz — Can you document how to use that option in
https://github.com/perl6/doc/blob/616e6b0e0afa4f0b95afb295bac48ced90fa6d50/README.md#L83

and/or in
https://github.com/perl6/doc/blob/616e6b0e0afa4f0b95afb295bac48ced90fa6d50/CONTRIBUTING.md#L250

and then we can close this out?

**Comment by JJ** [comment] 2019-07-22 05:56
@treyharris it's not deployed yet here.

**Comment by coke** [comment] 2023-02-03 16:46
This is now a problem for doc-website: see https://github.com/Raku/doc-website/blob/main/README.md#building-the-documentation-locally

**Closed by coke** 2023-02-03 16:46 UTC
Labels: build, site, wishlist
