### ISSUE TITLE
On Firefox, difficult to scroll through the table of contents on the left of each page

### ISSUE THREAD

**Issue by falsifian** [Raku/doc#4176] opened 2022-12-15 17:58 UTC
## Problem or new feature

See this screenshot: 
![2022-12-15-175315_1105x731_scrot](https://user-images.githubusercontent.com/225893/207932707-fe649a41-3a76-49db-98ca-c9c6168d6d02.png)
Note that I've scrolled halfway down the page, but the table of contents is still at the top.
In order to see the end of the TOC, it seems I need to scroll all the way to the bottom of the page.
Related: the behaviour when I search through the page in Firefox is confusing normally Firefox scrolls to the current search result, but it doesn't if the search result is in the TOC, so the search result often ends up being off-screen.

I tried it in Chromium and found the TOC scrolls with the rest of the page:
![2022-12-15-175517_1103x768_scrot](https://user-images.githubusercontent.com/225893/207933054-1380c820-be37-491e-b3fe-64b74635c303.png)
This seems much better to me, because it is much easier to scroll through the TOC (with the minor disadvantage that the TOC scrolls completely off-screen at some point).

**Comment by Altai-man** [comment] 2022-12-15 18:23
Hi!

What do you think about this: http://164.90.207.89:10010/language/operators#infix_(+),_infix_%E2%8A%8E ?

**Comment by falsifian** [comment] 2022-12-15 18:54
Oh, cool! It certainly solves this issue.

Some notes, after playing with it briefly:
- I clicked a section heading (Item assignment precedence) and was taken to the top of the document. That's a bit confusing; took me a moment to realize what had happened. Personally I'd suggest a more conventional "go to top" link.
- A minor annoyance: to use the TOC requires three steps: (1) click the ">"; (2) click the heading I want; (3) click the "<" to make the TOC go away so it doesn't cover up the content I just jumped to. Suggestion: instead of making the TOC overlap the content, how about shifting the content to the right when the TOC appears? (Or I guess you could have different behaviour depending on whether the browser window's wide enough to accommodate the TOC.)
- Running code doesn't seem to work; not sure if it's expected to in your demo.

**Comment by falsifian** [comment] 2022-12-15 18:55
>     * I clicked a section heading (Item assignment precedence) and was taken to the top of the document. That's a bit confusing; took me a moment to realize what had happened. Personally I'd suggest a more conventional "go to top" link.

I think I was expecting the whole section header to behave like the permalink, i.e. I expected the page to scroll so that it starts at that section. But I think I just clicked it because I was curious, really.

**Comment by codesections** [comment] 2022-12-15 20:10
> Note that I've scrolled halfway down the page, but the table of contents is still at the top.
In order to see the end of the TOC, it seems I need to scroll all the way to the bottom of the page.

I think this issue is still worth fixing on the current doc site – it is pretty annoying.  (I've noticed it too, but it started around the same time I switched distos so I thought the problem was on my end.  But it seems more widespread than that).

**Comment by codesections** [comment] 2022-12-15 20:18
After looking into it, this seems to be a regression caused by b2e1f8503948bc37226aa1295f9dd00ab1eeaf5b which added the `sticky` CSS property to the nav bar in response to #2138.  The quickest fix would be to revert that change, but then the problem it was solving (needing to scroll back up to the nav bar) would be would exist again.

**Comment by coke** [comment] 2022-12-15 23:01
> Hi!
> 
> What do you think about this: http://164.90.207.89:10010/language/operators#infix_(+),_infix_%E2%8A%8E ?

UI issues in the current site won't be fixed; we can't currently deploy any fixes and are working on deploying this new site; please verify if this issue exists in the new UI.

**Closed by coke** 2022-12-15 23:01 UTC
Labels: docs
