### ISSUE TITLE
Styling of types

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc#2954] opened 2019-08-15 16:27 UTC
## The problem

While proofreading some documentation pages (e.g., [types](https://docs.perl6.org/type)), I've noticed that when a particular type is mentioned, the type is either linked to (e.g., `L<Hash/type/Hash>`), formatted as code (e.g., `C<Hash>`) or just plain text (e.g., `Hash`). In some instances, the same type is linked to multiple times over the length of the page. Other times, it's never linked to but just formatted as code. In other, it's just plain text w/o any formatting that blends with the surrounding text.

## Suggestions

Most type pages have two top-level sections: the introduction to the type (e.g., `class Hash`) which follows the class's title and subtitle and the Methods (and Type Graph) sections. In the following paragraphs, I'll focus only on the introduction section which itself might have sections. The case for routines documentation under the Methods section seems to be [already covered here](https://github.com/perl6/doc/commit/0d57bfa1d37e6948ab941f661c2474475dd4bf8f#diff-da89ae830582df8fe02e0957d2ee00f0R35-R38). Thus depending on how these pages are meant to be read, we could've some sort of convention when styling the types in the introduction:

* **Top-to-bottom**. If each type page is meant to be read from top-to-bottom, then:
    
     - The first time a type is mentioned, we should link to it (`L<>`). Subsequent mentions (regardless if it's in the same section, same section's subsection, new section, etc.) should be formatted as `C<>` accordingly.
     - References to types and other constructs in a specific code example should be formatted with `C<>`. However, some exceptions may apply.

* **Granular**. If each type page is meant to be read granular-ly, then:

     - In a single h1-level section, the first time a type is mentioned we should link to it (`L<>`) and subsequent mentions of it within the same section (and its subsections) should be formatted as `C<>`. New mentions of the same type in other h1-level sections follow the same procedure.
     - References to types and other constructs in a specific code example still should be formatted with `C<>`. However, some exceptions may apply.

**Comment by JJ** [comment] 2019-08-15 20:25
I see merit in your argument. The problem is to actually enforce it. Either we get expert proofreaders, or we have somehow to develop an xt test to check that. If that's the case, I'd happily adopt that policy (if everyone else is happy with it)

**Comment by coke** [comment] 2023-03-05 19:49
Adding onto the new [xt/rakudoc-c.rakutest] in origin/type-links.

Lots of e.g.`C<Hash>` - the WIP test is recommending these appear as C<L<Hash|/type/Hash>>.

**Comment by coke** [comment] 2023-03-05 20:25
Given how secondary doc pages are generated, we should use the same formatting on each element on the page, not just the first - we can't guarantee ordering is the same on primary sources vs. generated pages.

**Comment by coke** [comment] 2024-05-18 03:50
This test has been merged to main - work is in progress to make all doc files pass, and this will unify the styling.

**Comment by coke** [comment] 2024-05-18 03:51
Note that the test does not require an initial link and then code-style, but always requires the link.

**Comment by coke** [comment] 2024-05-18 16:27
Test failures now counted by file:

```
# You failed 198 tests of 427
```

**Comment by coke** [comment] 2024-05-21 22:29
Down to 25 failures, all of the type listed above - Closing this ticket - having the xt/ test will ensure no new docs are added that break the styling, and I'll open tickets for these (probably a specific one for how to write "method Str", and a generic one to handle AST/JS Set, etc.

**Closed by coke** 2024-05-21 22:29 UTC
Labels: xt
