### ISSUE TITLE
HAS is not indexed

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3475] opened 2020-06-14 08:35 UTC
## Problem or new feature

The "embedded" version of `has` is documented [here](https://stackoverflow.com/a/50745483/891440) (sorta), but not indexed.

## Suggestions

Describe it properly, and also some usage patterns.

**Comment by Altai-man** [comment] 2020-06-19 22:38
Closed as duplicate of https://github.com/Raku/doc/issues/2965

**Closed by Altai-man** 2020-06-19 22:38 UTC
Labels: docs
