### ISSUE TITLE
"p6doc" modulename is misleading

### ISSUE THREAD

**Issue by patrickbkr** [Raku/doc#3644] opened 2020-09-16 19:19 UTC
Over in https://github.com/Raku/App-Rakubrew/issues/25 someone got confused, because apparently the `p6doc` module does not install a `p6doc` command line tool anymore. I agree that this is misleading (especially given the module description of "Raku documentation (tools and docs)").

Suggestion:
- Rename the module to something else not "p6doc" so it doesn't overlap with the deprecated command line tool. First thing that comes to mind: "raku-documentation"
- Change the description to make it clear that it's not the command line tool that the module installs. Maybe: "Official Raku documentation"

**Comment by Altai-man** [comment] 2020-09-17 07:30
I think there is work going to migrate to `rakudoc`, can search this repo tickets for more info.

**Comment by JJ** [comment] 2020-09-17 07:36
rakudoc is a separate utility, that has been already published.

The main problem here is if we want, or not, this repo to be a module in the ecosystem or not. This is probably not the right place to do this, and we should go to a problem-solving ticket, but I think that since most of the uses of this documentation (mainly, rakudoc or website generation) do *not* make use of the fact that it's available on the ecosystem, we might as well unpublish it.
If we decide to publish it in the ecosystem, we need to decide a name, and also follow standard procedure for installation. That would imply moving all docs to resource/, for instance, as requested in #3206 

So, respect to the original post by @patrickbkr renaming it would probably be a good first pase. The problem is that I'm not sure what kind of stuff it will break (I can think of Rakudo Star, but there's probably more we should think about). At any rate, it would be a breaking change that we need to consider *very* carefully.

**Comment by coke** [comment] 2022-04-16 16:36
installing documentation hadn't worked for years before spinning off p6doc, so there was nothing to break in R*.

Given that p6doc has spun off and this repo has been renamed, the original complaint on this ticket is gone, as far as I can see.

There are already other tickets in the repo for addressing related issues discussed in comments; closing this one.

**Closed by coke** 2022-04-16 16:36 UTC
Labels: meta
