### ISSUE TITLE
Bad URL https://docs.raku.org/raku.html

### ISSUE THREAD

**Issue by nooninm** [Raku/doc#3792] opened 2021-02-03 00:25 UTC
On page https://docs.raku.org/   the verbiage "view everything in one file" is supposed to be a link and should lead to https://docs.raku.org/raku.html.  However, https://docs.raku.org/raku.html does not exist, so I get a 404: Page Not Found error message.

No need to reply.
Good luck

**Comment by JJ** [comment] 2021-02-03 06:49
Thanks for the report. It's not been updated for some time. Actually duplicate of #2585

**Comment by coke** [comment] 2021-02-05 20:04
Closing as duplicate, please follow other ticket for updates.

**Closed by coke** 2021-02-05 20:04 UTC
