### ISSUE TITLE
Improve bless docs

### ISSUE THREAD

**Issue by JJ** [Raku/doc#2077] opened 2018-05-29 19:25 UTC
## The problem

The [`bless`](https://docs.perl6.org/routine/bless) does not clarify that `bless` calls the superclass constructor. It also says:

> (Though each time you write a custom constructor, remember that it makes subclassing harder).

Which is not exactly clear what it means. Why is it harder?

## Suggestion

Add example of calling the superclass constructor and change or clarify that sentence.

**Comment by JJ** [comment] 2018-06-01 07:13
Sorry, I will reopen this. It does not show how to call the superclass constructor using `bless`.
And while knowing about the peculiar `new` conventions might be a bit more difficult than knowing about class properties, which are initialized using their names, it's not such a big deal. You can also have as many  `new` as you want...

**Comment by fluca1978** [comment] 2018-06-01 07:27
You cannot call the superclass constructor using bless: bless does return a new instance and invokes buildall on that, that in turn walks the parent class hierarchy to call other constructors.
It is not clear to me what you mean with "improve" in this context, I suspect you should come up with a working small example of code.

**Comment by JJ** [comment] 2018-06-01 07:50
El vie., 1 jun. 2018 a las 9:28, Luca Ferrari (<notifications@github.com>)
escribió:

> You cannot call the superclass constructor using bless: bless does return
> a new instance and invokes buildall on that, that in turn walks the parent
> class hierarchy to call other constructors.
>

I think you actually can. I'll try to create an example

> It is not clear to me what you mean with "improve" in this context, I
> suspect you should come up with a working small example of code.
>

I'll try; if I can't, I will leave it closed. Thanks for understanding.

**Comment by fluca1978** [comment] 2018-06-01 08:06
This is my understanding:

1) `Mu.bless` does create the object and than calls BUILDALL

```
    method bless(*%attrinit) {
        nqp::create(self).BUILDALL(Empty, %attrinit);
    }
```

2) `Mu.new` does the same in the case no `bless` has been defined, or calls `bless` it it has been defined
```
    multi method new(*%attrinit) {
        nqp::if(
          nqp::eqaddr(
            (my $bless := nqp::findmethod(self,'bless')),
            nqp::findmethod(Mu,'bless')
          ),
          nqp::create(self).BUILDALL(Empty, %attrinit),
          nqp::invokewithcapture($bless,nqp::usecapture)
        )
    }
```

that means to me that `bless` is invoked by `new`, not viceversa. The `BUILDALL` is the key in constructor inheritance chain.

**Comment by JJ** [comment] 2018-06-01 08:41
[This example](https://github.com/JJ/my-perl6-examples/blob/master/does-dna-bless.p6) uses `bless` to initialize the superclass, which is `Str` in this case.

**Comment by fluca1978** [comment] 2018-06-01 09:14
This is a case of wrong initialization:

```
class Person {
  has $.name;
 multi method new( $a, $b ){ 
   my $name = $a ~ ',' ~ $b;
  self.bless( :$name );
 }
}

class Child is Person {
  multi method new( $name ){ self.bless( :$name ); }
}
```

there is no way in the child positional constructor to specify the surname, so the initialization performed by Person.new is not honored.
Probably there are other cases.

**Comment by fluca1978** [comment] 2018-06-01 09:21
> This example uses bless to initialize the superclass, which is Str in this case.

Yes, of course, calling BUILDALL with an hash. What I was saying is that there is no way to call `new` via `bless`, since `bless` calls `BUILDALL`. At least, this is what I see.

**Comment by JJ** [comment] 2018-06-01 09:32
And I'm trying to see now how bless calls BUILDALL--- to no avail.

**Comment by fluca1978** [comment] 2018-06-01 09:32
Let me reset.
The problem is that sentence about "implementing `new` is poor practice".
The fact is that using `bless` does mean calling `BUILDALL` and therefore `BUILD` on parent class, not `new` on parent class. That is the problem: you implement an initiliazation (`new`) that is not called back by subclasses.

**Comment by fluca1978** [comment] 2018-06-01 09:37
In other words: the initialization is `bless` -> `BUILDALL` -> `BUILD`.
Period.
The fact that there is a method called `new` that triggers `bless` (and thererfore the above) is just a convention. Placing a different `new` does not interrupts the above `bless`->`BUILD` chain, but everything outside such chain will not be executed by subclasses.

**Comment by JJ** [comment] 2018-06-01 09:38
El vie., 1 jun. 2018 a las 11:34, Luca Ferrari (<notifications@github.com>)
escribió:

> Let me reset.
> The problem is that sentence about "implementing new is poor practice".
>

I don't really have much to say about that. I opened the issue because it
was not clear why that was the case. It should be qualified why it's a bad
practice. For instance, in this code:

class Person {
    has $.name;
    multi method new( $a, $b ){
        my $name = $a ~ ',' ~ $b;
        self.bless( :$name );
    }

}

class Child is Person {}

my $kid = Child.new("Joss", "Whedon");
say $kid;

new is automatically inherited by Child. If you leave the default new, it
will have to use also positionals to do the same.

**Comment by JJ** [comment] 2018-06-01 09:40
El vie., 1 jun. 2018 a las 11:37, Luca Ferrari (<notifications@github.com>)
escribió:

> In other words: the initialization is bless -> BUILDALL -> BUILD.
>

That's quite clear.

> Period.
> The fact that there is a method called new that triggers bless (and
> thererfore the above) is just a convention. Placing a different new does
> not interrupts the above bless->BUILD chain, but everything outside such
> chain will not be executed by subclasses.
>

However, new in a subclass will call BUILDALL and then BUILD in that
subclass, even if the actual new that's been run is implemented in the
superclass. Let me see if I can create an example for that.

**Comment by JJ** [comment] 2018-06-01 09:54
For instance, [in this example](https://github.com/JJ/my-perl6-examples/blob/master/use-new.p6) `Child` uses `new` from parent class, which then uses `BUILD` from child class

**Comment by JJ** [comment] 2018-06-01 11:10
El vie., 1 jun. 2018 a las 12:23, Luca Ferrari (<notifications@github.com>)
escribió:

> I suspect I'm talking about something else:
>
> class Person {
>   multi method new( $a, $b ){
>     self.bless( :$a, :$b );
>     my-cool-post-initializer( $a, $b );
>  }
> }
>
> if you inherit from such class and *do* implement new again, you are
> leaving out my-cool-post-initializer because it is not within BUILD scope.
> That is why, in my opinion, it is a bad practice.
>

As I have said before, I'm not against the fact that new is a bad practice,
and I didn't reopen the issue for that reason. It might have seem so since
I keep using new in my examples above, but in this particular issue, my
only intention is to make clear why new is a bad idea.

**Comment by patrickbkr** [comment] 2020-10-24 18:30
I think the documentation on `bless` and object construction in general can be improved even more. I'm already working on a PR: #3671
I'll reopen this ticket for the purpose of discussing the changes and hope to be able to close this ticket with that PR. (Suggested by @JJ)

**Closed** 2020-10-26 09:09 UTC
Labels: docs, update
